import React, { createContext, useContext, useState, type ReactNode } from 'react';

type Language = 'en' | 'hi' | 'mr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    app_name: 'KisanSathi',
    home: 'Home',
    schemes: 'Schemes',
    my_farm: 'My Farm',
    applications: 'Applications',
    // Landing
    tagline: 'AI-Assisted Scheme Discovery for Farmers',
    hero_title: 'Find Government Schemes Made for You',
    hero_sub: 'Tell us about your farm and what help you need. KisanSathi will help you discover schemes that may match your information.',
    find_schemes_cta: 'Find Schemes for Me',
    tell_need_cta: 'Tell Us What You Need',
    speak_btn: '🎤 Speak',
    feat_find: 'Find Schemes',
    feat_benefits: 'Understand Benefits',
    feat_voice: 'Voice Assistance',
    feat_apply: 'Apply with Guidance',
    feat_find_desc: 'Discover schemes suited to your farm, location and needs.',
    feat_benefits_desc: 'Understand what benefits you may receive in simple language.',
    feat_voice_desc: 'Get assistance in your language by speaking or listening.',
    feat_apply_desc: 'Fill applications step-by-step with voice-assisted guidance.',
    // Onboarding
    onboarding_title: 'Tell Us About Yourself',
    step_you: 'About You',
    step_location: 'Location',
    step_farm: 'Farm',
    step_crop: 'Crop',
    step_need: 'What You Need',
    next: 'Next →',
    back: '← Back',
    name_label: 'Your Name',
    name_placeholder: 'Enter your full name',
    age_label: 'Your Age',
    age_placeholder: 'Enter your age',
    gender_label: 'Gender',
    gender_male: 'Male',
    gender_female: 'Female',
    gender_other: 'Other',
    category_label: 'Farmer Category',
    cat_marginal: 'Marginal Farmer (< 1 ha)',
    cat_small: 'Small Farmer (1-2 ha)',
    cat_medium: 'Medium Farmer (2-10 ha)',
    cat_large: 'Large Farmer (> 10 ha)',
    cat_women: 'Women Farmer',
    cat_sc: 'SC/ST Farmer',
    // Location
    loc_title: 'Where is Your Farm?',
    state_label: 'State',
    district_label: 'District',
    taluka_label: 'Taluka',
    village_label: 'Village',
    state_placeholder: 'Select State',
    district_placeholder: 'Select District',
    // Farm
    farm_title: 'About Your Farm',
    land_area_label: 'Total Land Area',
    land_unit_label: 'Unit',
    acres: 'Acres',
    hectares: 'Hectares',
    irrigation_label: 'Do you have irrigation?',
    yes: 'Yes',
    no: 'No',
    irrigation_type_label: 'Irrigation Type',
    drip: 'Drip',
    sprinkler: 'Sprinkler',
    canal: 'Canal',
    well: 'Well / Borewell',
    // Crop
    crop_title: 'What Do You Grow?',
    crop_label: 'Crop Name',
    crop_placeholder: 'e.g. Wheat, Rice, Cotton',
    season_label: 'Season',
    kharif: 'Kharif',
    rabi: 'Rabi',
    zaid: 'Zaid',
    perennial: 'Perennial',
    area_label: 'Cultivated Area',
    add_crop: '+ Add Another Crop',
    // Need
    need_title: 'What Help Do You Need?',
    need_sub: 'Select all that apply, or speak to tell us.',
    need_seeds: 'Seeds & Inputs',
    need_irrigation: 'Irrigation',
    need_machinery: 'Farm Machinery',
    need_financial: 'Financial Assistance',
    need_crop_support: 'Crop Support',
    need_insurance: 'Crop Insurance',
    need_organic: 'Organic Farming',
    need_horticulture: 'Horticulture',
    need_processing: 'Farm Processing',
    need_loans: 'Loans & Credit',
    need_training: 'Training & Support',
    need_all: 'Show All Schemes',
    find_matching: 'Find Matching Schemes →',
    // Schemes
    schemes_title: 'Schemes That May Help You',
    potentially_eligible: 'Potentially Eligible',
    more_info_needed: 'More Info Needed',
    not_matching: 'Not Matching',
    view_details: 'View Details →',
    why_matched: 'Why this appeared:',
    missing_info: 'More information needed:',
    benefit_label: 'Potential Benefit',
    // Scheme Detail
    what_is_scheme: 'What is this scheme?',
    who_benefits: 'Who can benefit?',
    what_benefit: 'What benefit is available?',
    why_recommended: 'Why was this recommended?',
    eligibility: 'Eligibility Conditions',
    documents: 'Required Documents',
    how_to_apply: 'How to Apply',
    official_source: 'Official Source',
    last_verified: 'Last verified',
    listen_btn: '🔊 Listen',
    apply_now: 'Apply for this Scheme',
    go_official: 'Continue to Official Portal →',
    official_notice: 'You are going to the official government website.',
    // Documents
    doc_why: 'Why is this required?',
    doc_where: 'Where to obtain it?',
    // Voice
    voice_idle: 'Speak instead of typing',
    voice_listening: 'Listening...',
    voice_processing: 'Processing...',
    voice_error: 'Could not understand. Please try again or type.',
    voice_denied: 'Microphone access unavailable. Please type instead.',
    // Review
    review_title: 'Review Your Application',
    submit_review: 'Looks Good — Continue',
    edit: 'Edit',
    missing_required: 'Required field is missing',
    // Errors
    required_field: 'This field is required.',
    loading: 'Loading...',
    no_schemes: 'No matching schemes found. Try updating your profile.',
  },
  hi: {
    app_name: 'किसानसाथी',
    home: 'होम',
    schemes: 'योजनाएं',
    my_farm: 'मेरा खेत',
    applications: 'आवेदन',
    tagline: 'किसानों के लिए AI-सहायता प्राप्त योजना खोज',
    hero_title: 'आपके लिए बनी सरकारी योजनाएं खोजें',
    hero_sub: 'हमें अपने खेत और ज़रूरतों के बारे में बताएं। किसानसाथी आपके लिए उपयुक्त योजनाएं खोजेगा।',
    find_schemes_cta: 'मेरे लिए योजनाएं खोजें',
    tell_need_cta: 'हमें बताएं आपको क्या चाहिए',
    speak_btn: '🎤 बोलें',
    feat_find: 'योजनाएं खोजें',
    feat_benefits: 'लाभ समझें',
    feat_voice: 'आवाज़ सहायता',
    feat_apply: 'मार्गदर्शन से आवेदन करें',
    feat_find_desc: 'अपने खेत, स्थान और ज़रूरतों के अनुसार योजनाएं खोजें।',
    feat_benefits_desc: 'सरल भाषा में समझें कि आपको क्या लाभ मिल सकता है।',
    feat_voice_desc: 'अपनी भाषा में बोलकर या सुनकर सहायता प्राप्त करें।',
    feat_apply_desc: 'आवाज़-सहायता के साथ चरण-दर-चरण आवेदन भरें।',
    onboarding_title: 'अपने बारे में बताएं',
    step_you: 'आपके बारे में',
    step_location: 'स्थान',
    step_farm: 'खेत',
    step_crop: 'फसल',
    step_need: 'आपकी ज़रूरत',
    next: 'अगला →',
    back: '← पिछला',
    name_label: 'आपका नाम',
    name_placeholder: 'अपना पूरा नाम लिखें',
    age_label: 'आपकी उम्र',
    age_placeholder: 'अपनी उम्र लिखें',
    gender_label: 'लिंग',
    gender_male: 'पुरुष',
    gender_female: 'महिला',
    gender_other: 'अन्य',
    category_label: 'किसान श्रेणी',
    cat_marginal: 'सीमांत किसान (< 1 हेक्टेयर)',
    cat_small: 'लघु किसान (1-2 हेक्टेयर)',
    cat_medium: 'मध्यम किसान (2-10 हेक्टेयर)',
    cat_large: 'बड़े किसान (> 10 हेक्टेयर)',
    cat_women: 'महिला किसान',
    cat_sc: 'अनुसूचित जाति/जनजाति किसान',
    loc_title: 'आपका खेत कहाँ है?',
    state_label: 'राज्य',
    district_label: 'जिला',
    taluka_label: 'तालुका',
    village_label: 'गाँव',
    state_placeholder: 'राज्य चुनें',
    district_placeholder: 'जिला चुनें',
    farm_title: 'आपके खेत के बारे में',
    land_area_label: 'कुल भूमि क्षेत्र',
    land_unit_label: 'इकाई',
    acres: 'एकड़',
    hectares: 'हेक्टेयर',
    irrigation_label: 'क्या आपके पास सिंचाई है?',
    yes: 'हाँ',
    no: 'नहीं',
    irrigation_type_label: 'सिंचाई का प्रकार',
    drip: 'ड्रिप',
    sprinkler: 'स्प्रिंकलर',
    canal: 'नहर',
    well: 'कुआँ / बोरवेल',
    crop_title: 'आप क्या उगाते हैं?',
    crop_label: 'फसल का नाम',
    crop_placeholder: 'जैसे गेहूँ, चावल, कपास',
    season_label: 'मौसम',
    kharif: 'खरीफ',
    rabi: 'रबी',
    zaid: 'जायद',
    perennial: 'बारहमासी',
    area_label: 'खेती क्षेत्र',
    add_crop: '+ एक और फसल जोड़ें',
    need_title: 'आपको किस मदद की ज़रूरत है?',
    need_sub: 'सभी जो लागू हों चुनें, या बोलकर बताएं।',
    need_seeds: 'बीज और इनपुट',
    need_irrigation: 'सिंचाई',
    need_machinery: 'कृषि मशीनरी',
    need_financial: 'वित्तीय सहायता',
    need_crop_support: 'फसल सहायता',
    need_insurance: 'फसल बीमा',
    need_organic: 'जैविक खेती',
    need_horticulture: 'बागवानी',
    need_processing: 'कृषि प्रसंस्करण',
    need_loans: 'ऋण और क्रेडिट',
    need_training: 'प्रशिक्षण और समर्थन',
    need_all: 'सभी योजनाएं दिखाएं',
    find_matching: 'मिलती योजनाएं खोजें →',
    schemes_title: 'योजनाएं जो आपकी मदद कर सकती हैं',
    potentially_eligible: 'संभावित रूप से पात्र',
    more_info_needed: 'अधिक जानकारी चाहिए',
    not_matching: 'मेल नहीं खाती',
    view_details: 'विवरण देखें →',
    why_matched: 'यह क्यों दिखाई दी:',
    missing_info: 'अधिक जानकारी आवश्यक:',
    benefit_label: 'संभावित लाभ',
    what_is_scheme: 'यह योजना क्या है?',
    who_benefits: 'इससे कौन लाभान्वित हो सकता है?',
    what_benefit: 'कौन सा लाभ उपलब्ध है?',
    why_recommended: 'यह क्यों अनुशंसित किया गया?',
    eligibility: 'पात्रता शर्तें',
    documents: 'आवश्यक दस्तावेज़',
    how_to_apply: 'आवेदन कैसे करें',
    official_source: 'आधिकारिक स्रोत',
    last_verified: 'अंतिम सत्यापित',
    listen_btn: '🔊 सुनें',
    apply_now: 'इस योजना के लिए आवेदन करें',
    go_official: 'आधिकारिक पोर्टल पर जारी रखें →',
    official_notice: 'आप आधिकारिक सरकारी वेबसाइट पर जा रहे हैं।',
    doc_why: 'यह क्यों आवश्यक है?',
    doc_where: 'इसे कहाँ से प्राप्त करें?',
    voice_idle: 'टाइप करने की बजाय बोलें',
    voice_listening: 'सुन रहे हैं...',
    voice_processing: 'प्रक्रिया हो रही है...',
    voice_error: 'समझ नहीं आया। फिर कोशिश करें या टाइप करें।',
    voice_denied: 'माइक्रोफ़ोन उपलब्ध नहीं। कृपया टाइप करें।',
    review_title: 'अपना आवेदन समीक्षा करें',
    submit_review: 'ठीक है — जारी रखें',
    edit: 'संपादित करें',
    missing_required: 'आवश्यक फ़ील्ड गायब है',
    required_field: 'यह फ़ील्ड आवश्यक है।',
    loading: 'लोड हो रहा है...',
    no_schemes: 'कोई मिलती योजना नहीं मिली। अपनी प्रोफ़ाइल अपडेट करें।',
  },
  mr: {
    app_name: 'किसानसाथी',
    home: 'होम',
    schemes: 'योजना',
    my_farm: 'माझी शेती',
    applications: 'अर्ज',
    tagline: 'शेतकऱ्यांसाठी AI-सहाय्यित योजना शोध',
    hero_title: 'तुमच्यासाठी बनलेल्या सरकारी योजना शोधा',
    hero_sub: 'आम्हाला तुमच्या शेती आणि गरजांबद्दल सांगा. किसानसाथी तुमच्यासाठी योग्य योजना शोधेल.',
    find_schemes_cta: 'माझ्यासाठी योजना शोधा',
    tell_need_cta: 'आम्हाला सांगा काय हवे आहे',
    speak_btn: '🎤 बोला',
    feat_find: 'योजना शोधा',
    feat_benefits: 'फायदे समजून घ्या',
    feat_voice: 'आवाज साहाय्य',
    feat_apply: 'मार्गदर्शनासह अर्ज करा',
    feat_find_desc: 'तुमची शेती, ठिकाण आणि गरजांनुसार योजना शोधा.',
    feat_benefits_desc: 'सोप्या भाषेत समजून घ्या की तुम्हाला कोणता फायदा मिळू शकतो.',
    feat_voice_desc: 'तुमच्या भाषेत बोलून किंवा ऐकून साहाय्य मिळवा.',
    feat_apply_desc: 'आवाज-सहाय्यासह पायरी-पायरी अर्ज भरा.',
    onboarding_title: 'तुमच्याबद्दल सांगा',
    step_you: 'तुमच्याबद्दल',
    step_location: 'ठिकाण',
    step_farm: 'शेती',
    step_crop: 'पिके',
    step_need: 'तुमची गरज',
    next: 'पुढे →',
    back: '← मागे',
    name_label: 'तुमचे नाव',
    name_placeholder: 'पूर्ण नाव लिहा',
    age_label: 'तुमचे वय',
    age_placeholder: 'वय लिहा',
    gender_label: 'लिंग',
    gender_male: 'पुरुष',
    gender_female: 'स्त्री',
    gender_other: 'इतर',
    category_label: 'शेतकरी प्रकार',
    cat_marginal: 'अल्पभूधारक शेतकरी (< 1 हेक्टर)',
    cat_small: 'लघु शेतकरी (1-2 हेक्टर)',
    cat_medium: 'मध्यम शेतकरी (2-10 हेक्टर)',
    cat_large: 'मोठे शेतकरी (> 10 हेक्टर)',
    cat_women: 'महिला शेतकरी',
    cat_sc: 'अनुसूचित जाती/जमाती शेतकरी',
    loc_title: 'तुमची शेती कुठे आहे?',
    state_label: 'राज्य',
    district_label: 'जिल्हा',
    taluka_label: 'तालुका',
    village_label: 'गाव',
    state_placeholder: 'राज्य निवडा',
    district_placeholder: 'जिल्हा निवडा',
    farm_title: 'तुमच्या शेतीबद्दल',
    land_area_label: 'एकूण जमिनीचे क्षेत्र',
    land_unit_label: 'एकक',
    acres: 'एकर',
    hectares: 'हेक्टर',
    irrigation_label: 'तुमच्याकडे सिंचन आहे का?',
    yes: 'हो',
    no: 'नाही',
    irrigation_type_label: 'सिंचनाचा प्रकार',
    drip: 'ठिबक',
    sprinkler: 'तुषार',
    canal: 'कालवा',
    well: 'विहीर / बोअरवेल',
    crop_title: 'तुम्ही काय पिकवता?',
    crop_label: 'पिकाचे नाव',
    crop_placeholder: 'उदा. गहू, तांदूळ, कापूस',
    season_label: 'हंगाम',
    kharif: 'खरीप',
    rabi: 'रब्बी',
    zaid: 'उन्हाळी',
    perennial: 'बारमाही',
    area_label: 'लागवड क्षेत्र',
    add_crop: '+ आणखी एक पीक जोडा',
    need_title: 'तुम्हाला कोणती मदत हवी आहे?',
    need_sub: 'सर्व लागू पर्याय निवडा, किंवा बोलून सांगा.',
    need_seeds: 'बियाणे आणि इनपुट',
    need_irrigation: 'सिंचन',
    need_machinery: 'शेती यंत्रसामग्री',
    need_financial: 'आर्थिक सहाय्य',
    need_crop_support: 'पीक सहाय्य',
    need_insurance: 'पीक विमा',
    need_organic: 'सेंद्रिय शेती',
    need_horticulture: 'फलोत्पादन',
    need_processing: 'शेती प्रक्रिया',
    need_loans: 'कर्ज आणि क्रेडिट',
    need_training: 'प्रशिक्षण आणि समर्थन',
    need_all: 'सर्व योजना दाखवा',
    find_matching: 'जुळणाऱ्या योजना शोधा →',
    schemes_title: 'तुम्हाला मदत करू शकणाऱ्या योजना',
    potentially_eligible: 'संभाव्यतः पात्र',
    more_info_needed: 'अधिक माहिती आवश्यक',
    not_matching: 'जुळत नाही',
    view_details: 'तपशील पहा →',
    why_matched: 'हे का दिसले:',
    missing_info: 'अधिक माहिती आवश्यक:',
    benefit_label: 'संभाव्य फायदा',
    what_is_scheme: 'ही योजना काय आहे?',
    who_benefits: 'कोणाला फायदा होऊ शकतो?',
    what_benefit: 'कोणता फायदा उपलब्ध आहे?',
    why_recommended: 'हे का शिफारस केले गेले?',
    eligibility: 'पात्रतेच्या अटी',
    documents: 'आवश्यक कागदपत्रे',
    how_to_apply: 'अर्ज कसा करावा',
    official_source: 'अधिकृत स्रोत',
    last_verified: 'शेवटी सत्यापित',
    listen_btn: '🔊 ऐका',
    apply_now: 'या योजनेसाठी अर्ज करा',
    go_official: 'अधिकृत पोर्टलवर सुरू ठेवा →',
    official_notice: 'तुम्ही अधिकृत सरकारी वेबसाइटवर जात आहात.',
    doc_why: 'हे का आवश्यक आहे?',
    doc_where: 'ते कुठून मिळवावे?',
    voice_idle: 'टाइप करण्याऐवजी बोला',
    voice_listening: 'ऐकत आहे...',
    voice_processing: 'प्रक्रिया होत आहे...',
    voice_error: 'समजले नाही. पुन्हा प्रयत्न करा किंवा टाइप करा.',
    voice_denied: 'मायक्रोफोन उपलब्ध नाही. कृपया टाइप करा.',
    review_title: 'तुमचा अर्ज तपासा',
    submit_review: 'ठीक आहे — पुढे जा',
    edit: 'संपादित करा',
    missing_required: 'आवश्यक फील्ड गहाळ आहे',
    required_field: 'हे फील्ड आवश्यक आहे.',
    loading: 'लोड होत आहे...',
    no_schemes: 'कोणत्याही जुळणाऱ्या योजना सापडल्या नाहीत. तुमची प्रोफाइल अपडेट करा.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};

export type { Language };
