"""
Payment Pydantic models for Razorpay checkout order creation, verification, and status responses.
"""

from typing import Optional, Any, Dict
from pydantic import BaseModel, Field, ConfigDict


class PaymentOrderCreateRequest(BaseModel):
    """Payload for initiating a Razorpay payment order from cart with delivery address."""
    shipping_address: str = Field(..., min_length=3, description="Street / village address")
    shipping_city: str = Field(..., min_length=2, description="City / district")
    shipping_state: str = Field(..., min_length=2, description="State")
    shipping_pincode: str = Field(..., min_length=4, max_length=10, description="Postal PIN code")


class RazorpayPrefill(BaseModel):
    """Prefill information for Razorpay Checkout Modal."""
    name: Optional[str] = None
    contact: Optional[str] = None
    email: Optional[str] = None


class RazorpayOrderResponse(BaseModel):
    """Response returned to client to initialize Razorpay checkout."""
    order_id: str = Field(..., description="AgriMart internal database order ID")
    razorpay_order_id: str = Field(..., description="Razorpay generated order ID")
    amount: int = Field(..., description="Amount in Indian paise (1 INR = 100 paise)")
    currency: str = Field(default="INR", description="Currency code")
    key_id: str = Field(..., description="Public Razorpay Key ID (safe for frontend)")
    prefill: Optional[RazorpayPrefill] = None

    model_config = ConfigDict(from_attributes=True)


class PaymentVerifyRequest(BaseModel):
    """Payload sent by client after successful Razorpay checkout to verify HMAC signature."""
    order_id: str = Field(..., description="AgriMart database order ID")
    razorpay_order_id: str = Field(..., description="Razorpay order ID returned by gateway")
    razorpay_payment_id: str = Field(..., description="Razorpay payment ID returned by gateway")
    razorpay_signature: str = Field(..., description="HMAC-SHA256 signature generated by Razorpay")


class PaymentVerifyResponse(BaseModel):
    """Response after payment signature validation."""
    success: bool
    message: str
    order_id: str
    payment_status: str
    order: Optional[Dict[str, Any]] = None


class PaymentStatusResponse(BaseModel):
    """Status polling response for an order."""
    order_id: str
    status: str
    payment_status: str
